### ISSUE TITLE
Difficult to contribute to from behind a proxy

### ISSUE THREAD

**Issue by incandescant** [crops/yocto-dockerfiles#16]
I'm not sure if this is something we can address directly or whether we just need to help potential contributors find the right documentation, but the containers are difficult to build behind a proxy.

I've got docker talking to the proxy based on Docker's documentation:
https://docs.docker.com/engine/admin/systemd/#http-proxy

I've got a WIP patch to pass the host's proxy configuration to docker build with the --build-arg option, which prevents the proxy configuration from persisting in the image. This is good because it helps build the images behind a proxy when one is configured on the host and doesn't pollute generated images with variables from a user's host:
https://github.com/incandescant/yocto-dockerfiles/commit/faab857b3e2e34f23ca1dfb1a4fbf798cea94f51

However smoke testing fails because the image isn't configured with a proxy, and I'm not sure how to address that short of setting ENV variables in the Dockerfile which are specific to my setup and thus can't be included in this repo.

Any thoughts/suggestions gratefully received!

**Comment by bavery22** [comment]
2 thoughts. 
1) chameleonsocks - https://github.com/crops/chameleonsocks kind of a big hammer and needs to run privileged, but it should work.
2) make a patch to the tests to accept proxy info, then inject the proxy information into the containers at run time for the tests.
