### ISSUE TITLE
Ubuntu dockerfile

### ISSUE THREAD

**Issue by ghost** [crops/yocto-dockerfiles#21]
I'm runing a dockerfile as 
> docker build yocto-dockerfiles/dockerfiles/ubuntu/ubuntu-16.04/ubuntu-16.04-base/

but I got this
```
Step 3/7 : COPY build-install-dumb-init.sh /
COPY failed: stat /var/lib/docker/tmp/docker-builder697770929/build-install-dumb-init.sh: no such file or directory

```

how to use a dockerfile correctly?

**Comment by bavery22** [comment]
Probably the easiest is to do:

yocto-dockerfiles$ REPO=local DISTRO_TO_BUILD=ubuntu-16.04
./build_container.sh

This hides some of the magic.

**Comment by peter73421** [comment]
two images created

```
> REPOSITORY          TAG                    IMAGE ID            CREATED             SIZE
> local               ubuntu-16.04-builder   162ba138626d        About an hour ago   725MB
> local               ubuntu-16.04-base      9ef4a5b55956        About an hour ago   725MB
>  
```
can run *-base but not *-builder mage ...

```
> ubuntu@ubuntu:~/work/dockers/yocto-dockerfiles$ docker run -i -t local:ubuntu-16.04-builder
> runbitbake.py: error: argument --pokydir is required
> runbitbake.py: error: argument --target/-t is required
> 
```
how to use it?
can I have sudo under yoctouser since need install stuff?

**Comment by bavery22** [comment]
builder is designed to run YP commands. It is a work in progress and is not
well documented. run :

docker run -it --rm local:ubuntu-16.04-builder  --help

for info.

to install stuff, once the container is running, do a $docker exec -it
--user=root <container id > bash from a different shell. Then you will be
in the same container as root.

**Comment by peter73421** [comment]
Understand, I'd like to "dockerize" Yocto image build and its extSDK. I wanna have a Docker(s) of Yocto build and its extSDK for App development with Eclipse ADT to be distributed to other developers. So I hope these "yocto-dockerfiles" can be used.
