### ISSUE TITLE
Deploy new Image to DockerHub

### ISSUE THREAD

**Issue by mnsgs** [crops/yocto-dockerfiles#32]
With Ubuntu 18.10 added recently, are there any chance of getting this deployed to DockerHub?

Thanks,
Martin

**Comment by rewitt1** [comment]
This should already be added to dockerhub based on https://github.com/crops/yocto-dockerfiles/blob/14f155c23b8f41d034d7d130ac699317bb99a91b/.travis.yml#L24

However that's not the case, so I'll have to investigate the problem. I'm sorry for the delay in responding, I'm just swamped with unrelated work. But still, apologies.

**Comment by mnsgs** [comment]
No problem Randy, appreciate the fact that we at all have docker images :)

**Comment by rewitt1** [comment]
Ubuntu 18.10 should now be in the images. I also made sure it was added to crops/poky-container.
