### ISSUE TITLE
Ubuntu 16.04 fails to build "ImportError: no module named 'zipp'"

### ISSUE THREAD

**Issue by moto-timo** [crops/yocto-dockerfiles#41]
Collecting zipp>=0.5 (from importlib-metadata<2,>=0.12; python_version < "3.8"->virtualenv)
  Downloading https://files.pythonhosted.org/packages/60/85/668bca4a9ef474ca634c993e768f12bd99af1f06bb90bb2655bc538a967e/zipp-2.2.0.tar.gz
  Running setup.py (path:/tmp/pip-build-jtbm_jam/zipp/setup.py) egg_info for package zipp produced metadata for project name unknown. Fix your #egg=zipp fragments.
Building wheels for collected packages: distlib, unknown, unknown
  Running setup.py bdist_wheel for distlib: started
  Running setup.py bdist_wheel for distlib: finished with status 'done'
  Stored in directory: /root/.cache/pip/wheels/6e/e8/db/c73dae4867666e89ba3cfbc4b5c092446f0e584eda6f409cbb
  Running setup.py bdist_wheel for unknown: started
  Running setup.py bdist_wheel for unknown: finished with status 'done'
  Stored in directory: /root/.cache/pip/wheels/a0/1f/9d/d132b3fbc38b33322681e3a7830c0a29fce7f55c3a06b85c65
  Running setup.py bdist_wheel for unknown: started
  Running setup.py bdist_wheel for unknown: finished with status 'error'
  Failed building wheel for unknown
  Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-jtbm_jam/unknown/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" bdist_wheel -d /tmp/tmpuwb3ou1bpip-wheel- --python-tag cp35:
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/usr/lib/python3.5/tokenize.py", line 454, in open
      buffer = _builtin_open(filename, 'rb')
  FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-build-jtbm_jam/unknown/setup.py'
  
  ----------------------------------------
  Running setup.py clean for unknown
  Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-jtbm_jam/unknown/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" clean --all:
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/usr/lib/python3.5/tokenize.py", line 454, in open
      buffer = _builtin_open(filename, 'rb')
  FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-build-jtbm_jam/unknown/setup.py'
  
  ----------------------------------------
  Failed cleaning build dir for unknown
Successfully built distlib unknown
Failed to build unknown
Installing collected packages: appdirs, six, unknown, importlib-metadata, distlib, importlib-resources, filelock, virtualenv
Successfully installed appdirs-1.4.3 distlib-0.3.0 filelock-3.0.12 importlib-metadata-1.5.0 importlib-resources-1.0.2 six-1.14.0 unknown-0.0.0 virtualenv-20.0.4
You are using pip version 8.1.1, however version 20.0.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Traceback (most recent call last):
  File "/usr/local/bin/virtualenv", line 7, in <module>
    from virtualenv.__main__ import run_with_catch
  File "/usr/local/lib/python3.5/dist-packages/virtualenv/__init__.py", line 3, in <module>
    from .run import cli_run
  File "/usr/local/lib/python3.5/dist-packages/virtualenv/run/__init__.py", line 9, in <module>
    from .plugin.activators import ActivationSelector
  File "/usr/local/lib/python3.5/dist-packages/virtualenv/run/plugin/activators.py", line 6, in <module>
    from .base import ComponentBuilder
  File "/usr/local/lib/python3.5/dist-packages/virtualenv/run/plugin/base.py", line 9, in <module>
    from importlib_metadata import entry_points
  File "/usr/local/lib/python3.5/dist-packages/importlib_metadata/__init__.py", line 9, in <module>
    import zipp
ImportError: No module named 'zipp'
The command '/bin/sh -c bash /build-install-dumb-init.sh &&      rm /build-install-dumb-init.sh &&      apt-get clean' returned a non-zero code: 1
The command "./build_container.sh" exited with 1.

**Comment by mandiaya** [comment]
I have the same issue

**Comment by rewitt1** [comment]
I need more info to understand what is being built and where. Ubuntu 16.04 is building successfully in ci, https://travis-ci.org/crops/yocto-dockerfiles/builds/657948444.

```DISTRO_TO_BUILD=ubuntu-16.04 REPO=test ./build_container.sh```
also works for me on Fedora 29.

**Comment by moto-timo** [comment]
Seems like this must just be an intermittent issue with pip install of zipp. Most recent local and travis build does not reproduce the error. Closing as it is not related to the Dockerfile(s) nor the metadata.
