### ISSUE TITLE
Downloaded tar file is not compared to expected hash before use.

### ISSUE THREAD

**Issue by tmcdonoughtx** [crops/yocto-dockerfiles#51]
Line 26 overwrites the file sha256sums with the patch file hash instead of appending.  This prevents line 28 from comparing the downloaded tar file to the expected hash value.

https://github.com/crops/yocto-dockerfiles/blob/06fd122da0849a9fab4c02f518ca4d231eb42727/build-install-dumb-init.sh#L26

**Comment by rewitt1** [comment]
Good catch! I'm curious what led you to finding it.

I should be able to fix this soon, since it's such a small change.

Thanks.

**Comment by rewitt1** [comment]
Fixed by 09b2576da84fda96571982c84d1426cd088293f3.
