### ISSUE TITLE
Expired Let's Encrypt root certificate

### ISSUE THREAD

**Issue by ostjean** [crops/yocto-dockerfiles#55]
On September 30th, the Let's Encrypt root certificate DST Root CA X3 has expired and was replaced by ISRG Root X1.

I'm trying to build yocto using the most recent crops/yocto:ubuntu-18.04-base image, however just trying to clone the poky git repo is failing:
```
fatal: unable to access 'https://git.yoctoproject.org/git/poky.git/': server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: none
```

I looked at the yocto guide and noticed they were using git:// instead of https://. While that does solve the issue for cloning poky, I now get issues while running bitbake:
```
fatal: unable to access 'https://anongit.freedesktop.org/git/gstreamer/common.git/': server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: none
```

This is not as easy to fix, because that would mean hunting for all broken https fetches and creating bbappends / modifying bb files in the standard layers to replace with git://, or http:// for non-git downloads.

The simpler option would be to update ca-certificates, but considering this image doesn't support sudo, we cannot update it in our build scripts. The dockerfiles would need to be updated to install the latest version of ca-certificates.

**Comment by jcormier** [comment]
https://github.com/jcormier/crops_poky

Created two docker images which grab the existing crops/poky:ubuntu-{18.04,20.04} images and updating ca-certificates.  Hopefully this is only a short term fix and crops will rebuild these images :/

```
docker run ghcr.io/jcormier/crops_poky:18.04 git clone https://git.linaro.org/toolchain/gcc.git
Status: Downloaded newer image for ghcr.io/jcormier/crops_poky:18.04
Cloning into 'gcc'...
```

**Comment by ostjean** [comment]
Sorry for the delay, I hadn't had time to come back to this as we made our own derived image to unblock ourselves.

It seems to be working now with the crops/yocto image too
```
$ docker pull crops/yocto:ubuntu-18.04-base
ubuntu-18.04-base: Pulling from crops/yocto
284055322776: Already exists 
d3533dfe3282: Pull complete 
2dcfb5e840d0: Pull complete 
3e3d93277be1: Pull complete 
Digest: sha256:22d5aeba3e9c4844eab150a463d27a33a65a76b43bfc873e50750c3fae7dc521
Status: Downloaded newer image for crops/yocto:ubuntu-18.04-base
docker.io/crops/yocto:ubuntu-18.04-base

$ docker run --rm -it crops/yocto:ubuntu-18.04-base git clone https://git.yoctoproject.org/git/poky.git/
Cloning into 'poky'...
remote: Enumerating objects: 1351, done.
remote: Counting objects: 100% (1351/1351), done.
remote: Compressing objects: 100% (733/733), done.
remote: Total 543379 (delta 904), reused 828 (delta 611), pack-reused 542028
Receiving objects: 100% (543379/543379), 179.82 MiB | 33.13 MiB/s, done.
Resolving deltas: 100% (394690/394690), done.

$ docker run --rm -it crops/yocto:ubuntu-18.04-base git clone https://anongit.freedesktop.org/git/gstreamer/common.git/
Cloning into 'common'...
remote: Enumerating objects: 3997, done.
remote: Counting objects: 100% (3997/3997), done.
remote: Compressing objects: 100% (1367/1367), done.
remote: Total 3997 (delta 2697), reused 3857 (delta 2616)
Receiving objects: 100% (3997/3997), 622.07 KiB | 2.53 MiB/s, done.
Resolving deltas: 100% (2697/2697), done.

```
