### ISSUE TITLE
miss python3-pip package

### ISSUE THREAD

**Issue by lijenchen** [crops/yocto-dockerfiles#79]
I try to search the Dockerfile for ubuntu and use docker history for check that the package python3-pip should be installed. 
I could not find it in the docker container while I try to use pip3 command, but the Dockerfile with install python3-pip option.
what's wrong with python3-pip package?

my steps
docker pull crops/yocto:ubuntu-22.04-base
docker history crops/yocto:ubuntu-22.04-base --no-trunc -H --format "table {{.CreatedBy}}\t"
docker run --rm -it crops/yocto:ubuntu-22.04-base bash
dpkg -l | grep python3 | grep pip

**Comment by sbarthelemy** [comment]
> but the Dockerfile with install python3-pip option.

Yes, it is installed [at this line](https://github.com/crops/yocto-dockerfiles/blob/487f50da128386c58c0760fb7603d7a283b05f51/dockerfiles/ubuntu/ubuntu-22.04/ubuntu-22.04-base/Dockerfile#L26)

But later on, [the build-install-dumb-init.sh script runs](https://github.com/crops/yocto-dockerfiles/blob/master/dockerfiles/ubuntu/ubuntu-22.04/ubuntu-22.04-base/Dockerfile#L65).
Which will reinstall (no-op) then [remove python3-pip](https://github.com/crops/yocto-dockerfiles/blob/487f50da128386c58c0760fb7603d7a283b05f51/build-install-dumb-init.sh#L26) python3-pip.

It looks like a bug to me.
